# Generated by Django 5.1.1 on 2025-01-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_sermon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/user.png', null=True, upload_to='personal_profile_images'),
        ),
    ]
