# Generated by Django 5.1.1 on 2024-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_churchleader_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
